import Navbar from "@/components/navbar";
import Socials from "@/components/socials";
import { CartStoreProvider } from "@/providers/cart-store-provider";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartStoreProvider>
          <SessionProvider>
            <Navbar />
            <Socials />
            {children}
          </SessionProvider>
        </CartStoreProvider>
      </body>
    </html>
  );
}
